import { addDoc } from 'firebase/firestore'
import { exercisesRef } from '../firebase/fbRefs'

const exercises = [
  {
    name: 'Peso muerto con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=7KL8SgCP4KQ',
    imgUrls: null,
    tags: ['gluteos', 'isquiotibiales', 'cuadriceps', 'gemelos', 'trapecios', 'espalda'],
    creatorId: '',
  },
  {
    name: 'Sentadilla con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=qe-vI_JBtjM',
    imgUrls: null,
    tags: ['cuadriceps', 'gluteos', 'isquiotibiales', 'gemelo', 'soleo', 'aductores'],
    creatorId: '',
  },
  {
    name: 'Peso muerto rumano con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=NIng2JWF1Rs',
    imgUrls: null,
    tags: ['isquiotibiales', 'gluteos', 'espalda'],
    creatorId: '',
  },
  {
    name: 'Sentadilla bulgara con mancuerna',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=IE3ZJezh-wc',
    imgUrls: null,
    tags: ['isquiotibiales', 'gluteos', 'aductores', 'cuadriceps', 'gemelos'],
    creatorId: '',
  },
  {
    name: 'Extension de piernas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=r7ZMTzfiICAc',
    imgUrls: null,
    tags: ['cuadriceps'],
    creatorId: '',
  },
  {
    name: 'Camilla femoral',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=r9BJr9qRszo',
    imgUrls: null,
    tags: ['isquiotibiales', 'gemelos'],
    creatorId: '',
  },
  {
    name: 'Elevacion de cadera con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=mLy4SfCEJZk',
    imgUrls: null,
    tags: ['gluteos', 'abdomen', 'isquiotibiales'],
    creatorId: '',
  },
  {
    name: 'Elevacion de gemelos sentado en máquina',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=Z27RhPA66_8',
    imgUrls: null,
    tags: ['gemelos'],
    creatorId: '',
  },
  {
    name: 'Zancadas con mancuernas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=Uw56z6JdWGY',
    imgUrls: null,
    tags: ['cuadriceps', 'isquiotibiales', 'gluteos', 'aductores', 'gemelos'],
    creatorId: '',
  },
  {
    name: 'Pull through',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=SL4FjYrvNZQ',
    imgUrls: null,
    tags: ['cuadriceps', 'isquiotibiales', 'gluteos', 'aductores', 'gemelos'],
    creatorId: '',
  },
  {
    name: 'Prensa',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=D1FvjYNX9QI',
    imgUrls: null,
    tags: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos'],
    creatorId: '',
  },
  {
    name: 'Maquina de abductores',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=A5Bz9bSPKUA',
    imgUrls: null,
    tags: ['abductores'],
    creatorId: '',
  },
  {
    name: 'Gemelos en máquina de pie',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=R9eS_1An8L0',
    imgUrls: null,
    tags: ['gemelos'],
    creatorId: '',
  },
  {
    name: 'Dominadas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=KFxrkDpRnFM',
    imgUrls: null,
    tags: ['espalda', 'pectoral', 'triceps', 'biceps'],
    creatorId: '',
  },
  {
    name: 'Dominadas con agarre supino',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=SG_gvhrRokw',
    imgUrls: null,
    tags: ['espalda', 'pectoral', 'triceps', 'biceps'],
    creatorId: '',
  },
  {
    name: 'Press de banco plano',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=JhcjQHkjklA',
    imgUrls: null,
    tags: ['pectoral', 'triceps', 'deltoide anterior'],
    creatorId: '',
  },
  {
    name: 'Press inclinado con mancuernas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=MkMf308jXww',
    imgUrls: null,
    tags: ['pectoral', 'triceps', 'deltoide anterior'],
    creatorId: '',
  },
  {
    name: 'Press militar con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=f3E1jQFRONs',
    imgUrls: null,
    tags: ['trapecio', 'hombros', 'pectoral', 'triceps'],
    creatorId: '',
  },
  {
    name: 'Remo con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=Rc84YlRhI60',
    imgUrls: null,
    tags: ['espalda', 'trapecios', 'deltoide posterior'],
    creatorId: '',
  },
  {
    name: 'Remo gironda',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=e98IFQpjL88',
    imgUrls: null,
    tags: ['espalda', 'antebrazos'],
    creatorId: '',
  },
  {
    // desde aca
    name: 'Press frances con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=Loxe7Gh-fwc',
    imgUrls: null,
    tags: ['triceps'],
    creatorId: '',
  },
  {
    name: 'Curl de biceps con mancuernas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=rqy0oxx__sU',
    imgUrls: null,
    tags: ['biceps'],
    creatorId: '',
  },
  {
    name: 'Curl de biceps con barra',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=KoHAlbeXtuA',
    imgUrls: null,
    tags: ['biceps'],
    creatorId: '',
  },
  {
    name: 'Face pull',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=h2I7pHAKLoE',
    imgUrls: null,
    tags: ['hombros'],
    creatorId: '',
  },
  {
    name: 'Extensión de triceps',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=dRkTreltpnc',
    imgUrls: null,
    tags: ['triceps'],
    creatorId: '',
  },
  {
    name: 'Elevacion lateral con mancuernas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=hgLpdwMtEEs',
    imgUrls: null,
    tags: ['hombros'],
    creatorId: '',
  },
  {
    name: 'Elevacion frontal con mancuernas',
    description: '',
    videoUrl: 'https://www.youtube.com/watch?v=MXJOvBh-Shw',
    imgUrls: null,
    tags: ['hombros'],
    creatorId: '',
  },
]

export default async function () {
  const promises = exercises.map((exercise) => addDoc(exercisesRef, exercise))
  Promise.all(promises).then(console.log).catch(console.error)
}
